version: '3.4'

services:
  hostedservice:
    image: otaviojulianons/hostedservice:latest
    ports:
      - "5000:80"
    environment: 
      - "Serilog__Elasticsearch__Enabled=true"
      - "Serilog__Elasticsearch__Path=logs/serilog.txt"
      - "Serilog__Elasticsearch__Url="
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.3.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
  logstash:
    image: logstash
    volumes:
      - ..\deploy\logstash-input-file.conf:/config-dir/logstash-input-file.conf
    command: logstash -f /config-dir/logstash-input-file.conf
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch 
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ..\deploy\prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment: 
      - "GF_SERVER_ROOT_URL=http://grafana.server.name"
      - "GF_SECURITY_ADMIN_PASSWORD=secret"


  
